@startuml
hide empty members
left to right direction

class Besoin
class "Tâche" as tache
class Release
class Doc
class Test
class Source

Besoin "1" o--> "*" tache
Test -left-> Source : vérifie
Release "1" o--> "*" Besoin
tache <|-- Doc
tache <|-- Source
tache <|-- Test
@enduml